- name: Remove any non-local root accounts
  command: 'mysql -NBe "{{ item }}"'
  with_items:
    DELETE FROM mysql.user WHERE User='{{ mariadb_root_username }}' AND Host NOT IN ('localhost', '127.0.0.1', '::1')
  changed_when: false

- name: Remove any plugins (auth_socket) from root user
  command: 'mysql -NBe "{{ item }}"'
  with_items:
    UPDATE mysql.user SET plugin = '' WHERE user = '{{ mariadb_root_username }}' AND host = 'localhost';
    FLUSH PRIVILEGES;
  changed_when: false

- name: Set root user password for local accounts
  mysql_user:
    host: "{{ item }}"
    name: "{{ mariadb_root_username }}"
    password: "{{ mariadb_root_password }}"
    check_implicit_admin: yes
    state: present
  with_items:
    - 127.0.0.1
    - ::1
    - localhost

- name: Create root .my.cnf file.
  template:
    src: user_my_cnf.j2
    dest: /root/.my.cnf
    owner: root
    group: root
    mode: 0600

- name: Remove any anonymous users
  mysql_user:
    user: ''
    host_all: yes
    state: absent

- name: Remove the test database
  mysql_db:
    name: test
    state: absent
